(()=>{if(window.__MFST_9331__)return;window.__MFST_9331__=true;
const DEFAULTS={win:10,place:10,qin:10,qpl:10,forecast:10,tierce:10,trio:10,first4:10,quartet:10,double:10,smartBudget:1000,autoSend:false};
const TYPE_MAP={win:'獨贏',place:'位置',qin:'連贏',qpl:'位置Q',forecast:'二重彩',tierce:'三重彩',trio:'單T',first4:'四連環',quartet:'四重彩',double:'孖寶'};
let settings={...DEFAULTS},type='qin',selected=new Set(),banker=null,field=false;const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function comb(n,k){if(k<0||n<k)return 0;if(k===0||n===k)return 1;let r=1;for(let i=1;i<=k;i++)r=r*(n-k+i)/i;return Math.round(r)}
function detectHorseCount(){let max=0;const text=document.body.innerText||'';for(const m of text.matchAll(/(?:^|\s)(\d{1,2})(?=\s)/g)){const v=+m[1];if(v>max&&v<=24)max=v}return Math.max(14,max)}
function countBets(){const n=selected.size;if(type==='win'||type==='place')return n;if(type==='qin'||type==='qpl'){if(banker&&field)return Math.max(0,detectHorseCount()-1);return comb(n,2)}if(type==='forecast')return n>1?n*(n-1):0;if(type==='trio')return comb(n,3);if(type==='tierce')return n>2?n*(n-1)*(n-2):0;if(type==='first4')return comb(n,4);if(type==='quartet')return n>3?n*(n-1)*(n-2)*(n-3):0;return n?1:0}
function stake(){return Number(settings[type]||10)}function total(){return countBets()*stake()}
function renderSummary(){const r=$('#mfst-root');if(!r)return;$('.mfst-summary',r).textContent=`${TYPE_MAP[type]}組合 ${countBets()} 注`;$('.mfst-summary2',r).textContent=`每注 $${stake()}　總投注 $${total()}`;$('.mfst-total',r).textContent=`已選：${[...selected].sort((a,b)=>a-b).join(', ')||'—'}${banker?'　膽：'+banker:''}${field?'　全餐':''}`;$$('.mfst-tab',r).forEach(b=>b.classList.toggle('active',b.dataset.type===type))}
function status(t){const el=$('#mfst-status');if(el)el.textContent=t}
function findBetRadio(label){for(const el of $$('label,span,div')){const tx=(el.textContent||'').trim();if(tx===label||tx.includes(label)){const radio=el.querySelector('input[type=radio]')||el.closest('label')?.querySelector('input[type=radio]');if(radio)return radio}}return null}
function syncToHKJC(){const radio=findBetRadio(TYPE_MAP[type]);if(radio){radio.click();radio.dispatchEvent(new Event('change',{bubbles:true}))}let matched=0;for(const n of selected){for(const row of $$('tr')){const first=(row.querySelector('td')?.textContent||'').trim();if(first===String(n)){const cb=row.querySelector('input[type=checkbox]');if(cb&&!cb.checked){cb.click();matched++}break}}}status(matched||radio?`已嘗試同步到馬會頁面（${matched} 匹）`:'找不到目前頁面的投注控制，請先開啟投注版面。')}
function sendBet(){syncToHKJC();if(!settings.autoSend){status('已加入頁面選擇；自動發送未開啟。');return}setTimeout(()=>{const btn=$$('button,a,input[type=button]').find(el=>/發送注項|送出|立即傳送|send bet/i.test((el.textContent||el.value||'').trim()));if(btn){btn.click();status('已按自動發送。')}else status('未找到馬會的發送按鈕，請手動確認。')},250)}
function smartCalc(){const budget=Math.max(0,Number(settings.smartBudget)||0),c=countBets();if(!c){status('先選擇馬匹。');return}const unit=Math.max(10,Math.floor((budget/c)/10)*10);status(`本機聰明計算：預算 $${budget}，${c} 注，建議每注約 $${unit}（不使用第三方會員算法）`)}
function build(){if($('#mfst-root'))return;const root=document.createElement('div');root.id='mfst-root';root.innerHTML=`<div class="mfst-head"><span class="title">跑馬地 - 1</span><button class="mfst-iconbtn" id="mfst-settings-btn">⚙︎</button><button class="mfst-iconbtn" id="mfst-close">×</button></div><div class="mfst-body"><div class="mfst-tabs">${Object.entries(TYPE_MAP).map(([k,v])=>`<button class="mfst-tab ${k==='qin'?'active':''}" data-type="${k}">${v}</button>`).join('')}<button class="mfst-tab quick" data-type="qin">快速</button><div style="color:#fff;text-align:center;font-size:11px;padding-top:4px">9.3.3 Local</div></div><div class="mfst-main"><div class="mfst-actions"><button id="mfst-add">加入注項</button><button class="send" id="mfst-send">自動發送</button><button id="mfst-del">🗑</button></div><button class="mfst-smart" id="mfst-smart">聰明計算</button><div class="mfst-summary"></div><div class="mfst-summary2"></div><div class="mfst-row"><button id="mfst-banker">膽</button><button id="mfst-field">全餐</button></div><div class="mfst-grid" id="mfst-grid"></div><div class="mfst-total"></div><div class="mfst-status" id="mfst-status">毋須登入；設定儲存在本機。</div><div class="mfst-settings" id="mfst-settings"><h3>設定注碼</h3><div class="mfst-sgrid">${Object.entries(TYPE_MAP).map(([k,v])=>`<label>${v}<input data-set="${k}" type="number" min="0" step="10"></label>`).join('')}<label>聰明投注總預算<input data-set="smartBudget" type="number" min="0" step="10"></label></div><label style="display:block;margin-top:8px"><input data-set="autoSend" type="checkbox"> 開啟自動發送模式</label><button class="mfst-save" id="mfst-save">儲存設定</button></div></div></div>`;document.body.appendChild(root);
const grid=$('#mfst-grid',root);for(let i=1;i<=14;i++){const b=document.createElement('button');b.className='mfst-num';b.textContent=i;b.dataset.n=i;grid.appendChild(b)}const f=document.createElement('button');f.className='mfst-num mfst-special';f.textContent='F';f.dataset.field='1';grid.appendChild(f);
root.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.classList.contains('mfst-tab')){type=t.dataset.type;selected.clear();banker=null;field=false;renderSummary();return}if(t.classList.contains('mfst-num')&&t.dataset.n){const n=+t.dataset.n;selected.has(n)?selected.delete(n):selected.add(n);t.classList.toggle('on',selected.has(n));renderSummary();return}if(t.dataset.field){field=!field;t.classList.toggle('on',field);renderSummary();return}switch(t.id){case'mfst-settings-btn':$('#mfst-settings').classList.toggle('open');break;case'mfst-close':root.classList.add('mfst-hide');break;case'mfst-del':selected.clear();banker=null;field=false;$$('.mfst-num',root).forEach(x=>x.classList.remove('on'));renderSummary();break;case'mfst-banker':banker=banker?null:[...selected][0]||null;t.classList.toggle('on',!!banker);renderSummary();break;case'mfst-field':field=!field;t.classList.toggle('on',field);renderSummary();break;case'mfst-add':syncToHKJC();break;case'mfst-send':sendBet();break;case'mfst-smart':smartCalc();break;case'mfst-save':{const ns={...settings};$$('[data-set]',root).forEach(el=>{ns[el.dataset.set]=el.type==='checkbox'?el.checked:Math.max(0,Number(el.value)||0)});settings=ns;chrome.storage.local.set({mfStandalone:settings},()=>status('設定已儲存'));renderSummary();break}}});
$$('[data-set]',root).forEach(el=>{const v=settings[el.dataset.set];if(el.type==='checkbox')el.checked=!!v;else el.value=v});renderSummary()}
chrome.storage.local.get({mfStandalone:DEFAULTS},({mfStandalone})=>{settings={...DEFAULTS,...mfStandalone};build()});})();